# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
  sim_control_mode: 1  # 0: position, 1: velocity

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint1:
      p: 100
      d: 1
      i: 0.1
      i_clamp: 100
    joint2:
      p: 100
      d: 1
      i: 0.1
      i_clamp: 100
    joint3:
      p: 100
      d: 1
      i: 0.1
      i_clamp: 100
    joint4:
      p: 10
      d: 0.1
      i: 0.01
      i_clamp: 100
    joint5:
      p: 20
      d: 0.2
      i: 0.02
      i_clamp: 100
    joint6:
      p: 1
      d: 0.01
      i: 0.001
      i_clamp: 100
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint7
  gains:
    joint7:
      p: 10000
      d: 0.1
      i: 0
      i_clamp: 1
